{% set python_min = '3.10' %}
{% set name = "onyxgenai" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MetroStar/onyx-genai-sdk/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4cb81b7f95c9bd6a3260513db3b1d6121b603f9bc3a85ed32288a667fb05a9b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - spacy
    - PyPDF2
    - python-pptx

test:
  imports:
    - onyxgenai
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/MetroStar/onyx-genai-sdk
  summary: 'Python SDK for interacting with Onyx Generative AI Services'
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbouder
