{% set name = "onyxgenai" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MetroStar/onyx-genai-sdk/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c63da84194a96257e9d051f189054de631b3f2aa9dc672fb2e4310e7794ffe1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - requests
    - spacy
    - PyPDF2
    - python-pptx

test:
  imports:
    - onyxgenai
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MetroStar/onyx-genai-sdk
  summary: 'Python SDK for interacting with Onyx Generative AI Services'
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbouder
